import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import 'flowbite';


import NavBar from "./components/Nav/NavBar";
import Footer_comp from "./components/Footer/Footer";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"></meta>
      </head>
      <body className={inter.className}>
        <NavBar/>
          <div>
             {children}
          </div>  
        <Footer_comp/>
      </body>
    </html>
  )
}
